-- MySQL Script generated by MySQL Workbench
-- 04/19/16 12:35:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tk2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tk2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tk2` DEFAULT CHARACTER SET utf8 ;
USE `tk2` ;

-- -----------------------------------------------------
-- Table `tk2`.`lintu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tk2`.`lintu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nimi` VARCHAR(45) NULL,
  `yleisyys` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tk2`.`kayttaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tk2`.`kayttaja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nimi` VARCHAR(45) NOT NULL,
  `salasana` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nimi_UNIQUE` (`nimi` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tk2`.`kala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tk2`.`kala` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nimi` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tk2`.`kuva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tk2`.`kuva` (
  `filename` VARCHAR(255) NOT NULL COMMENT 'Viittaa linnun ID:hen',
  `lintuid` INT NULL,
  `kalaid` INT NULL,
  PRIMARY KEY (`filename`),
  INDEX `const_kalaid_idx` (`kalaid` ASC),
  CONSTRAINT `const_lintuid`
    FOREIGN KEY (`lintuid`)
    REFERENCES `tk2`.`lintu` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `const_kalaid`
    FOREIGN KEY (`kalaid`)
    REFERENCES `tk2`.`kala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tk2`.`kunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tk2`.`kunta` (
  `nimi` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`nimi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tk2`.`lintuhavainto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tk2`.`lintuhavainto` (
  `lintu` INT NOT NULL,
  `paikka` VARCHAR(255) NULL DEFAULT 'Ei tiedossa',
  `id` INT NOT NULL AUTO_INCREMENT,
  `havaitsija` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `const_havaitsija_idx1` (`havaitsija` ASC),
  INDEX `const_paikka_idx1` (`paikka` ASC),
  CONSTRAINT `const_lintuid2`
    FOREIGN KEY (`lintu`)
    REFERENCES `tk2`.`lintu` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `const_lint_havaitsija`
    FOREIGN KEY (`havaitsija`)
    REFERENCES `tk2`.`kayttaja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `const_lintu_paikka`
    FOREIGN KEY (`paikka`)
    REFERENCES `tk2`.`kunta` (`nimi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tk2`.`kalahavainto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tk2`.`kalahavainto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paikka` VARCHAR(255) NULL DEFAULT 'Ei tiedossa',
  `pituus` INT NOT NULL,
  `kalaid` INT NOT NULL,
  `havaitsija` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `const_kalaid_idx2` (`kalaid` ASC),
  INDEX `const_havaitsija_idx2` (`havaitsija` ASC),
  INDEX `const_paikka_idx3` (`paikka` ASC),
  CONSTRAINT `const_kalaid3`
    FOREIGN KEY (`kalaid`)
    REFERENCES `tk2`.`kala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `const_kala_havaitsija`
    FOREIGN KEY (`havaitsija`)
    REFERENCES `tk2`.`kayttaja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `const_kalapaikka`
    FOREIGN KEY (`paikka`)
    REFERENCES `tk2`.`kunta` (`nimi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
